### ISSUE TITLE
how to navigate to next page on mobile phone

### ISSUE THREAD

**Issue by yangxuan8282** [kuanyui/takahashi.js#1]
on laptop we can use arrow key jump to next page,
but seems on mobile phone no method to do it

**Comment by kuanyui** [comment]
Yes, I didn't implement this function because I didn't have any Android device to test at the time I made this. However that should be easy.

**Comment by kuanyui** [comment]
I just added touch screen support, enjoy it. :D 
![tmp_20852-p_20170228_150426_vhdr_on698518068](https://cloud.githubusercontent.com/assets/1370070/23395108/dc902dbc-fdc7-11e6-864b-0cdbc6538a84.jpg)

**Comment by kuanyui** [comment]
Please check out

**Comment by yangxuan8282** [comment]
Thanks
It works great on mobile phone now.
By the way, I have built a docker image for arm devices ( i.e. raspberry pi):  [yangxuan8282/takahashijs](https://hub.docker.com/r/yangxuan8282/takahashijs/)
